repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: requirements-txt-fixer
    - id: check-json
    - id: pretty-format-json
      args: ["--autofix", "--indent", "4"]
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.14.3
  hooks:
    # TODO: There's probably a way to have check-jsonschema query whatever
    # schema is defined in the JSON's toplevel `$schema` key, but I haven't
    # been able to figure out how to do that yet. `check-metaschema` doesn't
    # seem to do what I want, so for now we just manually set the schemafile.
    - id: check-jsonschema
      files: settings.json
      args: ["--schemafile", "https://aka.ms/terminal-profiles-schema"]
